[package]
name = "serde_receive"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustecal = { path = "../../../rustecal", features = ["pubsub"] }
rustecal-types-serde = { path = "../../../rustecal-types-serde" }
