blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/eclipse-ecal/rustecal/discussions
    about: Ask questions or start a conversation with the community.
