[package]
name = "blob_send"
version = "0.1.0"
edition = "2021"

[dependencies]
rustecal = { path = "../../../rustecal", features = ["pubsub"] }
rustecal-types-bytes = { path = "../../../rustecal-types-bytes" }